config:
        mainpage: My Main Page
        space-prefix:
                ABC: "MY_NAMESPACE:ABC/"
                DEF: "MY_NAMESPACE:DEf/"
                GHI: "GHI_NAMESPACE:"
        categories:
                - My Category 1
                - My Category 2
        ext-ns-file-repo-compat: true
